include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - lib/amplify_gen/**.dart
    - lib/amplifyconfiguration.dart
linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    use_build_context_synchronously: false
    require_trailing_commas: true
    implicit_call_tearoffs: true
    unreachable_from_main: true

    # import
    prefer_relative_imports: true
    always_use_package_imports: false

    # 変数の宣言
    prefer_final_locals: true
    prefer_const_declarations: true
    always_declare_return_types: true

    # constructor
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_constructors_over_static_methods: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
