name: flutter_aws_workspace
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # immutable
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # Provider
  flutter_riverpod: ^2.3.5

  # AWS
  amplify_api: ^1.0.0
  amplify_flutter: ^1.0.0
  amplify_datastore: ^1.0.0-supports-only-mobile
  shared_aws_api: ^2.0.1
  aws_dax_api: ^2.0.0
  aws_dynamodb_api: ^2.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # lint
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.3.0

  # freezed
  freezed: ^2.2.0
  json_serializable: ^6.6.1

  # build_runner
  build_runner: ^2.3.3
flutter:
  uses-material-design: true
